{% set name = "pytransform3d" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd26b3b80ccf720fd7d65b71270b2c58df55d6f9ba47f4ade5ff9a30817b4a5e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - pip
    - python {{ python_min }}
    - scipy
  run:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytransform3d

about:
  home: https://github.com/dfki-ric/pytransform3d
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 3D transformations for Python
  doc_url: https://dfki-ric.github.io/pytransform3d/
  dev_url: https://github.com/dfki-ric/pytransform3d

extra:
  recipe-maintainers:
    - erikmannerfelt
    - AlexanderFabisch
