{% set name = "pytransform3d" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e64b6ba95f8c20e394fb5900e8d604d50c6b4b1ea36fff43ee8f84be6ecccf28

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - pip
    - python >=2.7
    - scipy
  run:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - python >=2.7
    - scipy

test:
  imports:
    - pytransform3d

about:
  home: https://github.com/dfki-ric/pytransform3d
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 3D transformations for Python
  doc_url: https://dfki-ric.github.io/pytransform3d/
  dev_url: https://github.com/dfki-ric/pytransform3d

extra:
  recipe-maintainers:
    - erikmannerfelt
    - AlexanderFabisch
