{% set name = "pytransform3d" %}
{% set version = "3.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8f83c06b6e30785c7d2c2cb538522b8bef682d3e4c4e0f789273a36a3836022

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - pip
    - python {{ python_min }}
    - scipy
    - setuptools
  run:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytransform3d

about:
  home: https://github.com/dfki-ric/pytransform3d
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 3D transformations for Python
  doc_url: https://dfki-ric.github.io/pytransform3d/
  dev_url: https://github.com/dfki-ric/pytransform3d

extra:
  recipe-maintainers:
    - erikmannerfelt
    - AlexanderFabisch
