{% set name = "pytransform3d" %}
{% set version = "3.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f43d525751f02d12fa785d48348e842b6cfe2d5d1c9c09301b23a682c42e4afb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - pip
    - python {{ python_min }}
    - scipy
    - setuptools
  run:
    - beautifulsoup4
    - lxml
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytransform3d

about:
  home: https://github.com/dfki-ric/pytransform3d
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 3D transformations for Python
  doc_url: https://dfki-ric.github.io/pytransform3d/
  dev_url: https://github.com/dfki-ric/pytransform3d

extra:
  recipe-maintainers:
    - erikmannerfelt
    - AlexanderFabisch
